### ISSUE TITLE
Unable to use with newly created Angular4 site using "ng new".  Issue with sourceFile['symbol'].exports

### ISSUE THREAD

**Issue by nicholasnafpliotis** [clbond/angular-ssr#28] opened 2017-05-02 16:25 UTC
These are the steps I take to reproduce the issue.  

1) ng new example
2) cd example
3) npm install
4) npm install --save angular-ssr
5) ng build
6) ./node_modules/.bin/ng-render

I get the following error:  

C:\tests\example\node_modules\angular-ssr\source\application\static\find.ts:16
  const exports: Map<string, any> = sourceFile['symbol'].exports;
                                                        ^
TypeError: Cannot read property 'exports' of undefined
    at Object.exports.exportClause (C:\Users\nick\Desktop\example\example\node_modules\angular-ssr\source\application\static\find.ts:16:57)
    at _loop_1 (C:\Users\nick\Desktop\example\example\node_modules\angular-ssr\source\application\static\modules\root.ts:60:29)
    at Object.exports.discoverRootModule (C:\Users\nick\Desktop\example\example\node_modules\angular-ssr\build\application\static\modules\root.js:59:9)
    at Object.exports.loadApplicationModule (C:\Users\nick\Desktop\example\example\node_modules\angular-ssr\source\application\compiler\options.ts:57:14)
    at WebpackCompiler.compile (C:\Users\nick\Desktop\example\example\node_modules\angular-ssr\source\application\compiler\webpack\compiler.ts:30:38)
    at ApplicationBuilderFromSource.build (C:\Users\nick\Desktop\example\example\node_modules\angular-ssr\source\application\builder\from-source.ts:18:29)
    at Object.<anonymous> (C:\Users\nick\Desktop\example\example\node_modules\angular-ssr\source\bin\render.ts:31:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\nick\Desktop\example\example\node_modules\angular-ssr\bin\render.js:3:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

I would like to figure out why this is happening myself, but when I go through the source, I'm having trouble figuring out the entire flow of the process.

So, my questions are if anyone knows what this issue could be, and also where to start looking to get a better feel for how this package works overall.

Thank You!

--nick

**Comment by nicholasnafpliotis** [comment] 2017-05-02 16:27
One of the first things I thought of was that it was failing because there was no routing going on, so I added a few basic routes, and I still get this same error.   I also tested this on my Mac and I get the same error as well, just in case it was a windows only issue.

**Comment by stratio84** [comment] 2017-05-04 13:05
I'm getting the exact same error in my project.

Do anyone has any idea on how to solve this problem?

Thanks

G.

**Comment by stratio84** [comment] 2017-05-06 12:45
I think it's missing a webpack configuration that causes this error.
@clbond do you have any idea how to overcome this issue?

Thanks,

G.

**Comment by stratio84** [comment] 2017-05-07 12:56
I managed to understand the problem and fix the issue. When you create a new project with "ng new" inside your tsconfig.app.json and tsconfig.spec.json files you will have this line:

`"extends": "../tsconfig.json"`

This line is causing the issue. If you delete it from both the files and import the config you need from the tsconfig.json directly inside the two files the ssr process will execute correctly.

G.

**Comment by clbond** [comment] 2017-05-11 16:28
You can avoid that error just by passing `--module relative/path/to/app.module` and `--symbol AppModule`. Replace those values with the path to your root module and the name of the symbol. That should fix the problem and let you use your normal tsconfigs. I will look into a proper fix when I get a bit of free time this weekend

**Comment by buu700** [comment] 2017-05-11 18:59
Manually flattening my tsconfigs works as expected, but the module/symbol workaround seems to consistently fail with this error:

```
[info] Rendering application from source (working path: /tmp/9c3c20b511c89)

<--- Last few GCs --->

[125:0x55cf5f8cf6f0]    95031 ms: Mark-sweep 1487.9 (1574.9) -> 1487.9 (1575.9) MB, 1192.4 / 0.0 ms  allocation failure GC in old space requested
[125:0x55cf5f8cf6f0]    96189 ms: Mark-sweep 1487.9 (1575.9) -> 1487.8 (1544.9) MB, 1156.7 / 0.0 ms  last resort
[125:0x55cf5f8cf6f0]    97359 ms: Mark-sweep 1487.8 (1544.9) -> 1487.8 (1544.9) MB, 1167.9 / 0.0 ms  last resort


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x15fa9bba66a1 <JS Object>
    1: slowToString(aka slowToString) [buffer.js:473] [pc=0x3840923cc3f5](this=0x1b9ab3b02311 <undefined>,buf=0x2d7e82b9a9f9 <an Uint8Array with map 0x23d77702c579>,encoding=0x15fa9bbaf309 <String[4]: utf8>,start=0,end=13777754)
    2: toString [buffer.js:~501] [pc=0x384092348896](this=0x2d7e82b9a9f9 <an Uint8Array with map 0x23d77702c579>,encoding=0x15fa9bbaf309 <String[4]: utf8>,start=0x1b9ab...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x55cf5cf6f61e [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::Factory::NewStringFromOneByte(v8::internal::Vector<unsigned char const>, v8::internal::PretenureFlag) [node]
 7: v8::internal::Factory::NewStringFromUtf8(v8::internal::Vector<char const>, v8::internal::PretenureFlag) [node]
 8: v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::String::NewStringType, int) [node]
 9: node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding) [node]
10: node::Buffer::Utf8Slice(v8::FunctionCallbackInfo<v8::Value> const&) [node]
11: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
12: 0x55cf5c6c715b [node]
13: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
14: 0x3840918843a7
/bin/bash: line 1:   125 Aborted                 ./node_modules/.bin/ng-render --module src/js/cyph.com/app.module.ts --symbol AppModule
```

**Comment by clbond** [comment] 2017-05-18 13:58
@buu700 Are you running this in a very low-memory environment?

**Comment by buu700** [comment] 2017-05-18 14:01
At the time I was running it in a Docker container with 2 GB allocated memory, but since then I've increased it to 4 GB to work around an unrelated issue with the Angular CLI (`ng serve` bug). I'll go ahead and test this again with the higher memory limit.

**Comment by clbond** [comment] 2017-05-18 14:19
Actually, I think I have resolved the issue that was causing your bug. Can you try with version `0.1.103` please? It was accidentally including all of `node_modules` when compiling the TypeScript (due to `ng new`s weird tsconfig.json structures)

**Comment by buu700** [comment] 2017-05-18 14:29
Awesome, sure, I'll report back here soon.

**Comment by clbond** [comment] 2017-05-18 15:14
I am not able to reproduce this issue anymore with projects created using `ng new`. I am pretty sure this issue is fixed but I'll wait to hear back from you before I close it

**Comment by buu700** [comment] 2017-05-18 16:23
Yep, confirmed that it's no longer reproducible for me.

**Closed** 2017-05-28 19:09 UTC
